/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetomauricio.Visao;

import Objetos.Equipamento;
import Objetos.Operacao;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetomauricio.DAO.BuscaRelatorio;
import projetomauricio.DAO.CarregaEquipamento;
import java.text.SimpleDateFormat;

/**
 *
 * @author Lucas
 */
public class Relatorio extends javax.swing.JFrame {

    Equipamento equipamento;
    List<Operacao> operacoes = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        CarregaFrota();
        setLocationRelativeTo(null);
        setExtendedState(6);
        tabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        boxFrota = new javax.swing.JComboBox();
        lblFrota = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEquipamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtInicial = new javax.swing.JFormattedTextField();
        txtFinal = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnGerarRelatorio = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabtleRelatorio = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        BtnPDF = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boxFrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFrotaActionPerformed(evt);
            }
        });

        lblFrota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrota.setText("Frota:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Equipamento:");

        lblEquipamento.setEditable(false);

        jLabel2.setText("Data Inicial:");

        try {
            txtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Data Final");

        BtnGerarRelatorio.setText("Gerar Relatório");
        BtnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGerarRelatorioActionPerformed(evt);
            }
        });

        TabtleRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabtleRelatorio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(TabtleRelatorio);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        BtnPDF.setText("Gerar PDF");
        BtnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblFrota, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boxFrota, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnGerarRelatorio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addComponent(btnLimpar)))
                        .addGap(18, 18, 18)
                        .addComponent(BtnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblFrota, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxFrota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(BtnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGerarRelatorio)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxFrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFrotaActionPerformed
        int valor = Integer.parseInt(boxFrota.getSelectedItem().toString());
        CarregaEquipamento(valor);
    }//GEN-LAST:event_boxFrotaActionPerformed

    private void BtnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGerarRelatorioActionPerformed
        limpar();
        try {

            DecimalFormat numero = new DecimalFormat("0.##");
            BuscaRelatorio dao = new BuscaRelatorio();
            Date inicial, fim = new Date();
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            inicial = df.parse(txtInicial.getText());
            fim = df.parse(txtFinal.getText());
            operacoes = dao.Relatorio(equipamento.getId(), inicial, fim);
            System.out.println(operacoes.size());
            String[] dados = new String[9];
            for (Operacao operacao : operacoes) {
                dados[0] = String.valueOf(operacao.getId());
                dados[1] = String.valueOf(numero.format(operacao.getHorasTrabalhadas()));
                dados[2] = String.valueOf(operacao.getAbastecimento());
                dados[3] = String.valueOf(numero.format(operacao.getMedia()));
                dados[4] = String.valueOf(operacao.getValorCombustivel());
                dados[5] = String.valueOf(operacao.getGastoTotal());
                if (operacao.getParada() == true) {
                    dados[6] = "sim";
                } else {
                    dados[6] = "não";
                }
                dados[7] = operacao.getMotivo();
                dados[8] = String.valueOf(equipamento.getFrota());
                modelo.addRow(dados);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Buscar relatório" + e);
        }

    }//GEN-LAST:event_BtnGerarRelatorioActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void BtnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPDFActionPerformed
        DecimalFormat numero = new DecimalFormat("0.##");
        SimpleDateFormat data = new SimpleDateFormat("dd-MM-yyyy HH-mm") {
        };
        Date nome = new Date();
        String teste = data.format(nome);
        System.out.println(teste);
        Document document = new Document();
        try {
            try {
                PdfWriter.getInstance(document, new FileOutputStream("C:\\LocalPDF/" + teste + ".pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            document.open();
            for (Operacao operacoe : operacoes) {
                document.add(new Paragraph("Número identificação da operação: " + operacoe.getId()));
                document.add(new Paragraph("Horas Trabalhadas: " + numero.format(operacoe.getHorasTrabalhadas())));
                document.add(new Paragraph("Quantidade combutível: " + operacoe.getAbastecimento()));
                document.add(new Paragraph("Média: " + numero.format(operacoe.getMedia())));
                document.add(new Paragraph("Valor do combustível: " + operacoe.getValorCombustivel()));
                document.add(new Paragraph("Soma dos gastos: " + operacoe.getGastoTotal()));
                if (operacoe.getParada() == true) {
                    document.add(new Paragraph("Efetuada a parada: Sim"));
                } else {
                    document.add(new Paragraph("Efetuada a parada: Não"));
                }
                document.add(new Paragraph("Motivo da parada: " + operacoe.getMotivo()));
                document.add(new Paragraph("Numero da Frota: " + equipamento.getFrota()));
                document.add(new Paragraph(""));
                document.add(new Paragraph("-----------------------------------------------------------------------"));
                document.add(new Paragraph(""));
            }
            document.addSubject("Gerando PDF em Java");
            document.addKeywords("www.devmedia.com.br");
            document.addCreator("iText");
        } catch (DocumentException de) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar o PDF" + de);
        }
        document.close();
    }//GEN-LAST:event_BtnPDFActionPerformed

    private void CarregaFrota() {
        CarregaEquipamento carega = new CarregaEquipamento();
        List<Equipamento> equipamentos = new ArrayList<>();
        equipamentos = carega.CarregaFrota();
        for (Equipamento equipamento : equipamentos) {
            boxFrota.addItem(equipamento.getFrota());
        }
    }

    private void CarregaEquipamento(int valor) {
        CarregaEquipamento carrega = new CarregaEquipamento();
        List<Equipamento> equipamentos = carrega.CarregaEquipamento(valor);
        equipamento = equipamentos.get(0);
        lblEquipamento.setText(equipamento.getEquipamento());
        Operacao opera = new Operacao();
        opera.setEquipamento(equipamento);
    }

    public void limpar() {
        modelo.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    public void tabela() {
        modelo.addColumn("ID");
        modelo.addColumn("Horas Trabalhadas");
        modelo.addColumn("Quantidade de combutível");
        modelo.addColumn("Média");
        modelo.addColumn("Valor do Combustível");
        modelo.addColumn("Gasto Total");
        modelo.addColumn("Efetuada a parada");
        modelo.addColumn("Motivo da parada");
        modelo.addColumn("Frota");

        TabtleRelatorio.setModel(modelo);
        TabtleRelatorio.getColumnModel().getColumn(0).setPreferredWidth(70);
        TabtleRelatorio.getColumnModel().getColumn(1).setPreferredWidth(168);
        TabtleRelatorio.getColumnModel().getColumn(2).setPreferredWidth(170);
        TabtleRelatorio.getColumnModel().getColumn(3).setPreferredWidth(100);
        TabtleRelatorio.getColumnModel().getColumn(4).setPreferredWidth(170);
        TabtleRelatorio.getColumnModel().getColumn(5).setPreferredWidth(100);
        TabtleRelatorio.getColumnModel().getColumn(6).setPreferredWidth(150);
        TabtleRelatorio.getColumnModel().getColumn(7).setPreferredWidth(270);
        TabtleRelatorio.getColumnModel().getColumn(8).setPreferredWidth(150);

//        TabtleRelatorio.setAutoResizeMode(TabtleRelatorio.setAutoResizeMode());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGerarRelatorio;
    private javax.swing.JButton BtnPDF;
    private javax.swing.JTable TabtleRelatorio;
    private javax.swing.JComboBox boxFrota;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lblEquipamento;
    private javax.swing.JLabel lblFrota;
    private javax.swing.JFormattedTextField txtFinal;
    private javax.swing.JFormattedTextField txtInicial;
    // End of variables declaration//GEN-END:variables
}
